" Vim syntax file for qkt strategy files. Generated by `qkt editor grammar --format vim`;
" edit src/main/kotlin/com/qkt/editor/ and regenerate rather than editing this file.

if exists("b:current_syntax") | finish | endif

" Identifier before a dot (lowest priority)
syn match qktAlias "\<\h\w*\ze\s*\."

" Broker prefix in BROKER:SYMBOL
syn match qktBroker "\<\h\w*:\ze\w"

" Symbol-form operators
syn match qktOperator "->\|==\|<>\|!=\|<=\|>=\|<\|>\|=\|+\|-\|\*\|/\|%"

" Named constants, scalar functions and indicators (calls need a following parenthesis)
syn match qktConstant "\c\<\%(BPS\|FIVE_PERCENT\|HALF_PERCENT\|ONE_PERCENT\|QUARTER_PERCENT\|TEN_PERCENT\|THREE_PERCENT\|TWO_PERCENT\)\>"
syn match qktFunction "\c\<\%(ABS\|AVG\|CALENDAR_WINDOW\|CEIL\|COUNT\|EXP\|FLOOR\|LAST_TRADING_DAY_OF_MONTH\|LOG\|MAX\|MEAN\|MIN\|MOD\|NORMALIZE\|POW\|RANK_OF\|ROUND\|ROUND_TO\|SESSION_WINDOW\|SOFTMAX\|SQRT\|SUM\)\>\ze\s*("
syn match qktIndicator "\c\<\%(ADX\|ANCHORED_RETURN\|ATR\|BETA\|BOLLINGER_LOWER\|BOLLINGER_MIDDLE\|BOLLINGER_UPPER\|CCI\|CONFIRM_RATIO\|CORRELATION\|DEMA\|EMA\|ER\|FAILED_BREAK_HIGH\|FAILED_BREAK_LOW\|GAP_FILL_FRACTION\|HIGHEST\|HMA\|IB_DEFENDED_HIGH\|IB_DEFENDED_LOW\|KELTNER_LOWER\|KELTNER_MIDDLE\|KELTNER_UPPER\|LAG\|LOWEST\|MACD\|MACD_HIST\|MACD_SIGNAL\|MINUS_DI\|OBV\|PERCENTILE_RANK\|PIVOT_P\|PIVOT_R1\|PIVOT_S1\|PLUS_DI\|REGRESSION_SLOPE\|REOPEN_GAP\|REOPEN_GAP_ORIGIN\|RESID\|RSI\|RUNLENGTH\|RUNLENGTH_WHERE\|SEASONAL_RANGE\|SEASONAL_RANGE_STDEV\|SESSION_MOMENTUM\|SESSION_RANGE_HIGH\|SESSION_RANGE_LOW\|SKEW\|SMA\|STDDEV\|STOCH_D\|STOCH_K\|TEMA\|VARIANCE\|VARIANCE_RATIO\|VWAP\|VWAP_SESSION\|VWAP_SESSION_STDEV\|WILLIAMS_R\|WMA\|ZSCORE\)\>\ze\s*("

" Keywords, one group per category
syn match qktSection "\c\<\%(BASKET\|DEFAULTS\|IMPORT\|LET\|PARAM\|PORTFOLIO\|REGIMES\|RULES\|SCHEDULE\|SEQUENCE\|SERIES\|STRATEGY\|SYMBOLS\|SYNCHRONIZE\|VERSION\)\>"
syn match qktFlow "\c\<\%(CASE\|DO\|EACH\|ELSE\|END\|EVERY\|FOR\|IN\|SINCE\|THEN\|WHEN\)\>"
syn match qktAction "\c\<\%(CANCEL\|CANCEL_ALL\|CLOSE_ALL\|DEBUG\|ERROR\|FLATTEN\|LOG\|WARN\)\>"
syn match qktAction "\c\<\%(BUY\|SELL\|CLOSE\|RESIZE\)\>" nextgroup=qktAliasTarget skipwhite
syn match qktOrder "\c\<\%(AT\|BY\|DAY\|FLOOR\|FOK\|GTC\|GTD\|IOC\|LIMIT\|MARKET\|ORDER_TYPE\|PCT\|STEP\|STOP\|STOP_LOSS\|TAKE_PROFIT\|TIF\|TIGHTEN\|TO\|TRAILING\|UNTIL\)\>"
syn match qktSizing "\c\<\%(BALANCE\|EQUITY\|MIN_STEP\|OF\|RISK\|SIZING\|USD\)\>"
syn match qktBracket "\c\<\%(AGAINST\|ARM\|BRACKET\|CLOSE_BEYOND\|CONFIRM\|ENTER\|EXPIRE\|FROM\|LATCH\|LOSS\|OCO\|OCO_ENTRY\|OFFSET\|ON\|PROFIT\|RETEST_HOLD\|RETRACE\|RR\|TAKE\|TIME_IN_BREACH\|WITH\)\>"
syn match qktStacking "\c\<\%(AFTER\|MAE\|MFE\|RECOVER\|SPACING\|STACK\|STACK_AT\|STAGE\|TIMES\|WITHIN\)\>"
syn match qktPortfolio "\c\<\%(ALLOCATE\|AS\|CAPITAL\|CASH\|DEFAULT\|EQUAL_WEIGHT\|HOLD\|METHOD\|NAME\|OVERRIDE\|REBALANCE\|RUN\|STATE\|WEIGHT\)\>"
syn match qktSession "\c\<\%(BARS\|BROKER\|CHICAGO\|HOUR\|LONDON\|NY\|SYDNEY\|TOKYO\|UTC\|WARMUP\|WEEKDAY\)\>"
syn match qktHook "\c\<\%(ON_CLOSE\|ON_FILL\|ON_STOP\|ON_TP\)\>"
syn match qktState "\c\<\%(ACCOUNT\|COOLDOWN\|ENTRY_QTY\|EXIT\|NOW\|OPEN_ORDERS\|POSITION\|POSITION_AVG_PRICE\|STREAK\|SYMBOL\|TRADES\)\>"
syn match qktOperatorWord "\c\<\%(ABOVE\|AND\|BELOW\|BETWEEN\|CROSSES\|IS\|NOT\|NULL\|OR\)\>"
syn match qktAggregate "\c\<\%(MAX\|MEAN\|MIN\|OPEN\|SUM\)\>"
syn match qktBoolean "\c\<\%(FALSE\|TRUE\)\>"
syn match qktAliasTarget contained "\<\h\w*\>"

" Any member after a dot, then the known stream fields and pseudo-symbol members
syn match qktMember "\.\zs\h\w*"
syn match qktField "\.\zs\c\<\%(ask\|avg_entry_price\|avg_price\|balance\|banked\|bid\|candle\|close\|complete\|contract\|contract_size\|count\|credit\|date_utc\|day\|days_in_month\|days_to_roll\|dd_pct\|delta\|dte\|entry_price\|epoch_ms\|equity\|equity_peak\|gamma\|gross\|high\|holding_duration\|hour_utc\|last_trade_at\|last_trade_pnl\|long_count\|longs\|loss_streak\|losses\|losses_today\|low\|mae\|max_loss\|mfe\|minute_utc\|month\|multiplier\|open\|open_count\|open_positions_count\|pnl\|pnl_pct\|price\|qty\|quantity\|realized_month\|realized_pnl\|realized_today\|reason\|remaining_s\|short_count\|shorts\|side\|spread\|stage\|swap_long_points\|swap_short_points\|theta\|tick\|tick_size\|tick_value\|time\|timestamp\|today\|total_pnl\|trades_today\|unrealized_pnl\|value\|vega\|volume\|volume_min\|volume_step\|weekday\|win_streak\|wins\|wins_today\)\>"

" Stream alias assigned a BROKER:SYMBOL in SYMBOLS
syn match qktAlias "^\s*\zs\h\w*\ze\s*=\s*\h\w*:"

" Numbers, then durations so they win over a plain number
syn match qktNumber "\<\d\+\(\.\d\+\)\?\([eE][+-]\?\d\+\)\?\>"
syn match qktDuration "\<\d\+[smhd]\>"

" Strings are single-line; only \\ \' \" \n \t are escapes, anything else is an error
syn match qktEscapeError contained "\\."
syn match qktEscape contained "\\[\\'\"nt]"
syn region qktString start=+"+ skip=+\\.+ end=+"+ oneline contains=qktEscape,qktEscapeError
syn region qktString start=+'+ skip=+\\.+ end=+'+ oneline contains=qktEscape,qktEscapeError

" Comments: line (--, #) and block (/* ... */)
syn match qktComment "--.*$" contains=@Spell
syn match qktComment "#.*$" contains=@Spell
syn region qktComment start="/\*" end="\*/" contains=@Spell

" Link to stock highlight groups so colorschemes pick them up
hi def link qktSection       PreProc
hi def link qktFlow          Conditional
hi def link qktAction        Statement
hi def link qktOrder         Keyword
hi def link qktSizing        Keyword
hi def link qktBracket       Keyword
hi def link qktStacking      Keyword
hi def link qktPortfolio     Keyword
hi def link qktSession       Keyword
hi def link qktHook          Keyword
hi def link qktState         Identifier
hi def link qktOperatorWord  Operator
hi def link qktAggregate     Function
hi def link qktBoolean       Boolean
hi def link qktAliasTarget   Identifier
hi def link qktAlias         Identifier
hi def link qktMember        Identifier
hi def link qktField         Constant
hi def link qktBroker        Type
hi def link qktOperator      Operator
hi def link qktConstant      Constant
hi def link qktFunction      Function
hi def link qktIndicator     Function
hi def link qktNumber        Number
hi def link qktDuration      Number
hi def link qktEscape        SpecialChar
hi def link qktEscapeError   Error
hi def link qktString        String
hi def link qktComment       Comment

let b:current_syntax = "qkt"
