package com.qkt.dsl.ast

enum class BinOp { ADD, SUB, MUL, DIV, AND, OR }

enum class UnOp { NEG, NOT }

enum class Cmp { GT, LT, GE, LE, EQ, NE }

enum class CrossDir { ABOVE, BELOW }

enum class AggFn { MIN, MAX, MEAN, SUM }

enum class StateSource {
    ACCOUNT,
    POSITION,
    POSITION_AVG_PRICE,
    POSITION_PNL,
    POSITION_REALIZED_PNL,
    POSITION_UNREALIZED_PNL,
    POSITION_HOLDING_DURATION,
    POSITION_MFE,
    POSITION_MAE,
    POSITION_OPEN_COUNT,
    POSITION_LONG_COUNT,
    POSITION_SHORT_COUNT,
    POSITION_GROSS,
    POSITION_TRADES_TODAY,
    POSITION_LAST_TRADE_AT,
    OPEN_ORDERS,
    STRUCTURE_DELTA,
    STRUCTURE_GAMMA,
    STRUCTURE_VEGA,
    STRUCTURE_THETA,
    STRUCTURE_DTE,
    STRUCTURE_CREDIT,
    STRUCTURE_MAX_LOSS,
    STRUCTURE_PNL_PCT,
}
