package com.qkt.editor

import com.qkt.dsl.parse.KeywordCategory

/**
 * Emits the Vim syntax file. Vim gives the item defined last priority when several start at the
 * same column, so rules are written in the reverse of the TextMate order: comments and strings
 * last, the bare-alias rules first. Every pattern carries `\c` to mirror the lexer's
 * case-insensitive keywords.
 */
internal object VimSyntax {
    private const val IDENT = "\\h\\w*"

    fun render(): String =
        buildString {
            appendLine("\" Vim syntax file for qkt strategy files. Generated by `qkt editor grammar --format vim`;")
            appendLine("\" edit src/main/kotlin/com/qkt/editor/ and regenerate rather than editing this file.")
            appendLine()
            appendLine("if exists(\"b:current_syntax\") | finish | endif")
            appendLine()
            appendLine("\" Identifier before a dot (lowest priority)")
            appendLine("syn match qktAlias \"\\<$IDENT\\ze\\s*\\.\"")
            appendLine()
            appendLine("\" Broker prefix in BROKER:SYMBOL")
            appendLine("syn match qktBroker \"\\<$IDENT:\\ze\\w\"")
            appendLine()
            appendLine("\" Symbol-form operators")
            appendLine("syn match qktOperator \"->\\|==\\|<>\\|!=\\|<=\\|>=\\|<\\|>\\|=\\|+\\|-\\|\\*\\|/\\|%\"")
            appendLine()
            appendLine("\" Named constants, scalar functions and indicators (calls need a following parenthesis)")
            appendLine("syn match qktConstant \"${words(GrammarVocabulary.constants)}\"")
            appendLine("syn match qktFunction \"${words(GrammarVocabulary.functions)}\\ze\\s*(\"")
            appendLine("syn match qktIndicator \"${words(GrammarVocabulary.indicators)}\\ze\\s*(\"")
            appendLine()
            appendLine("\" Keywords, one group per category")
            for (category in KeywordCategory.entries) appendLine(keywordRule(category))
            appendLine("syn match qktAliasTarget contained \"\\<$IDENT\\>\"")
            appendLine()
            appendLine("\" Any member after a dot, then the known stream fields and pseudo-symbol members")
            appendLine("syn match qktMember \"\\.\\zs$IDENT\"")
            appendLine("syn match qktField \"\\.\\zs${words(GrammarVocabulary.memberFields)}\"")
            appendLine()
            appendLine("\" Stream alias assigned a BROKER:SYMBOL in SYMBOLS")
            appendLine("syn match qktAlias \"^\\s*\\zs$IDENT\\ze\\s*=\\s*$IDENT:\"")
            appendLine()
            appendLine("\" Numbers, then durations so they win over a plain number")
            appendLine("syn match qktNumber \"\\<\\d\\+\\(\\.\\d\\+\\)\\?\\([eE][+-]\\?\\d\\+\\)\\?\\>\"")
            appendLine("syn match qktDuration \"\\<\\d\\+[smhd]\\>\"")
            appendLine()
            appendLine("\" Strings are single-line; only \\\\ \\' \\\" \\n \\t are escapes, anything else is an error")
            appendLine("syn match qktEscapeError contained \"\\\\.\"")
            appendLine("syn match qktEscape contained \"\\\\[\\\\'\\\"nt]\"")
            appendLine(
                "syn region qktString start=+\"+ skip=+\\\\.+ end=+\"+ oneline contains=qktEscape,qktEscapeError",
            )
            appendLine("syn region qktString start=+'+ skip=+\\\\.+ end=+'+ oneline contains=qktEscape,qktEscapeError")
            appendLine()
            appendLine("\" Comments: line (--, #) and block (/* ... */)")
            appendLine("syn match qktComment \"--.*$\" contains=@Spell")
            appendLine("syn match qktComment \"#.*$\" contains=@Spell")
            appendLine("syn region qktComment start=\"/\\*\" end=\"\\*/\" contains=@Spell")
            appendLine()
            appendLine("\" Link to stock highlight groups so colorschemes pick them up")
            for (category in KeywordCategory.entries) appendLine(link(category.vimGroup, category.vimLink))
            for ((group, target) in fixedLinks) appendLine(link(group, target))
            appendLine()
            appendLine("let b:current_syntax = \"qkt\"")
        }

    private val fixedLinks: List<Pair<String, String>> =
        listOf(
            "qktAliasTarget" to "Identifier",
            "qktAlias" to "Identifier",
            "qktMember" to "Identifier",
            "qktField" to "Constant",
            "qktBroker" to "Type",
            "qktOperator" to "Operator",
            "qktConstant" to "Constant",
            "qktFunction" to "Function",
            "qktIndicator" to "Function",
            "qktNumber" to "Number",
            "qktDuration" to "Number",
            "qktEscape" to "SpecialChar",
            "qktEscapeError" to "Error",
            "qktString" to "String",
            "qktComment" to "Comment",
        )

    private fun keywordRule(category: KeywordCategory): String {
        val plain = GrammarVocabulary.keywords(category) - GrammarVocabulary.aliasTakingActions.toSet()
        val rule = "syn match ${category.vimGroup} \"${words(plain)}\""
        if (category != KeywordCategory.ACTION) return rule
        val verbs = words(GrammarVocabulary.aliasTakingActions)
        return rule + "\n" + "syn match ${category.vimGroup} \"$verbs\" nextgroup=qktAliasTarget skipwhite"
    }

    /** A case-insensitive whole-word alternation in Vim regex syntax. */
    private fun words(names: List<String>): String = "\\c\\<\\%(" + names.joinToString("\\|") + "\\)\\>"

    private fun link(
        group: String,
        target: String,
    ): String = "hi def link %-16s %s".format(group, target)
}
