package com.qkt.notify

import com.qkt.common.Side
import java.math.BigDecimal

/**
 * Notification-layer event hierarchy. Translated from bus events (or generated by the
 * scheduler) at the [Notifier] boundary and consumed by [MessageTemplate] for delivery.
 *
 * Not an [com.qkt.events.Event] — does not flow through [com.qkt.bus.EventBus]. The
 * notifier subscribes to bus events and translates them into this hierarchy so we can
 * mix in scheduler-driven and lifecycle events that no other engine component cares about.
 */
sealed interface NotificationEvent {
    val timestamp: Long
    val severity: Severity

    enum class Severity { INFO, WARN, CRITICAL }

    data class OrderRejected(
        val strategyId: String,
        val symbol: String,
        val side: Side,
        val quantity: BigDecimal,
        val reason: String,
        override val timestamp: Long,
    ) : NotificationEvent {
        override val severity = Severity.CRITICAL
    }

    data class Halted(
        val strategyId: String?,
        val reason: String,
        override val timestamp: Long,
    ) : NotificationEvent {
        override val severity = Severity.CRITICAL
    }

    data class Resumed(
        val strategyId: String?,
        override val timestamp: Long,
    ) : NotificationEvent {
        override val severity = Severity.INFO
    }

    data class PositionReconciled(
        val strategyId: String,
        val symbol: String,
        val oldQty: BigDecimal?,
        val newQty: BigDecimal,
        val reason: String,
        override val timestamp: Long,
    ) : NotificationEvent {
        override val severity = Severity.WARN
    }

    data class StrategyStarted(
        val strategyId: String,
        override val timestamp: Long,
    ) : NotificationEvent {
        override val severity = Severity.INFO
    }

    data class StrategyStopped(
        val strategyId: String,
        val flatten: Boolean,
        override val timestamp: Long,
    ) : NotificationEvent {
        override val severity = Severity.INFO
    }

    data class StrategyError(
        val strategyId: String,
        val message: String,
        override val timestamp: Long,
    ) : NotificationEvent {
        override val severity = Severity.CRITICAL
    }

    data class DaemonStarted(
        val version: String,
        val strategies: List<String>,
        override val timestamp: Long,
    ) : NotificationEvent {
        override val severity = Severity.INFO
    }

    data class DailySummary(
        val asOfUtc: String,
        val strategies: List<StrategySummary>,
        override val timestamp: Long,
    ) : NotificationEvent {
        override val severity = Severity.INFO
    }
}

data class StrategySummary(
    val strategyId: String,
    val equity: BigDecimal,
    val equityDeltaPct: BigDecimal,
    val realizedToday: BigDecimal,
    val unrealized: BigDecimal,
    val tradesToday: Int,
    val haltsToday: Int,
    val positionsSummary: String,
)
