#!/usr/bin/env python3
"""Emit an instruments.yaml from a live MT5 gateway's own symbol metadata.

`StandardInstrumentRegistry` ships a small hand-maintained table: majors, three JPY pairs,
gold and silver. Anything else -- every cross, every CFD, every broker-suffixed symbol --
resolves to nothing, and a backtest on it fails closed rather than silently booking
contractSize=1. That is the right failure, but it leaves those instruments un-backtestable,
and it means the numbers a backtest prices with are a copy of the venue's rather than the
venue's own.

This reads `symbol_info` for each requested symbol and writes the registry a backtest loads,
so contract size, digits, point size, volume steps and swaps come from the same place live
gets them. Run it against the broker you actually trade, and the two agree by construction.

    scripts/instruments-from-gateway.py --gateway http://127.0.0.1:5001 \
        --symbols XAUUSDm,EURUSDm,EURJPYm --prefix EXNESS --out instruments.yaml
"""
import argparse
import json
import sys
import urllib.request


def fetch(gateway: str, symbol: str, api_key: str | None) -> dict:
    req = urllib.request.Request(f"{gateway}/symbol_info/{symbol}")
    if api_key:
        req.add_header("Authorization", f"Bearer {api_key}")
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def strip_suffix(symbol: str, suffix: str) -> str:
    return symbol[: -len(suffix)] if suffix and symbol.endswith(suffix) else symbol


def entry(qkt_symbol: str, info: dict) -> dict:
    for field in ("trade_contract_size", "volume_step", "volume_min", "point", "digits"):
        if info.get(field) is None:
            raise SystemExit(f"{qkt_symbol}: gateway did not report '{field}'")
    return {
        "qktSymbol": qkt_symbol,
        "contractSize": info["trade_contract_size"],
        "volumeStep": info["volume_step"],
        "volumeMin": info["volume_min"],
        "volumeMax": info.get("volume_max"),
        "pointSize": info["point"],
        "digits": int(info["digits"]),
        # MT5 reports stops level in points; 0 means the venue sets no minimum distance.
        "tradeStopsLevelPoints": int(info.get("trade_stops_level") or 0),
        # Swaps are per-lot points as the venue quotes them. Commission is NOT in symbol_info --
        # it is an account/group property -- so it stays 0 here and must be set deliberately.
        "swapLongPoints": info.get("swap_long") or 0,
        "swapShortPoints": info.get("swap_short") or 0,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--gateway", required=True)
    ap.add_argument("--symbols", required=True, help="comma-separated wire symbols, e.g. XAUUSDm,EURUSDm")
    ap.add_argument("--prefix", required=True, help="qkt broker prefix, e.g. EXNESS")
    ap.add_argument("--suffix", default="", help="broker wire suffix to strip, e.g. m")
    ap.add_argument("--api-key", default=None)
    ap.add_argument("--out", default="-")
    args = ap.parse_args()

    lines = [
        "# Generated by scripts/instruments-from-gateway.py -- do not hand-edit.",
        f"# Source: {args.gateway}",
        "instruments:",
    ]
    for wire in [s.strip() for s in args.symbols.split(",") if s.strip()]:
        info = fetch(args.gateway, wire, args.api_key)
        qkt_symbol = f"{args.prefix}:{strip_suffix(wire, args.suffix)}"
        row = entry(qkt_symbol, info)
        lines.append(f"  - qktSymbol: {row['qktSymbol']}")
        for key, value in row.items():
            if key == "qktSymbol" or value is None:
                continue
            lines.append(f"    {key}: {value}")
        print(f"  {qkt_symbol:<18} contract={row['contractSize']} digits={row['digits']} "
              f"point={row['pointSize']} profitCcy={info.get('currency_profit')}", file=sys.stderr)
    text = "\n".join(lines) + "\n"
    if args.out == "-":
        print(text)
    else:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"  wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
