package com.qkt.backtest.report

import com.qkt.backtest.BacktestResult
import com.qkt.backtest.DrawdownPeriod
import com.qkt.backtest.PerformanceReport
import com.qkt.backtest.TradeRecord
import java.nio.file.Files
import java.nio.file.Path

/**
 * Renders a [com.qkt.backtest.BacktestResult] as a self-contained HTML report —
 * headline cards, equity / drawdown / Monte-Carlo charts, per-strategy breakdowns,
 * and head / tail tables of individual trades.
 *
 * No external assets: all CSS, SVG, and data are inlined in the produced string,
 * so the report renders identically when opened offline or attached to an email.
 * Visual + statistical knobs live on [HtmlReportConfig].
 */
class HtmlReportWriter(
    private val config: HtmlReportConfig = HtmlReportConfig(),
) {
    /** Render the report and write it to [path]. Overwrites any existing file. */
    fun write(
        result: BacktestResult,
        path: Path,
    ) {
        Files.writeString(path, render(result))
    }

    /** Build the full HTML report as a single string. */
    fun render(result: BacktestResult): String {
        val sb = StringBuilder()
        sb.append("<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">")
        sb.append("<title>qkt backtest report</title>")
        sb.append("<style>${css()}</style></head><body>")

        sb.append("<header><h1>qkt backtest report</h1></header>")
        sb.append("<section class=\"headline\">")
        sb.append(headlineCards(result.global))
        sb.append("</section>")

        result.evidence?.let {
            sb.append("<section class=\"evidence\"><h2>Run evidence</h2>")
            sb.append(evidenceSection(it))
            sb.append("</section>")
        }
        result.accounting?.let {
            sb.append("<section class=\"accounting\"><h2>Accounting</h2>")
            sb.append(accountingSection(it))
            sb.append("</section>")
        }

        sb.append("<section class=\"equity\"><h2>Equity</h2>")
        sb.append(
            SvgChart.lineChartWithUnderwater(
                curve = result.global.equityCurve,
                drawdowns = result.global.drawdownPeriods,
                width = 1000,
                height = 360,
            ),
        )
        sb.append("</section>")

        sb.append("<section class=\"drawdowns\"><h2>Drawdown periods</h2>")
        sb.append(drawdownTable(result.global.drawdownPeriods))
        sb.append("</section>")

        sb.append("<section class=\"trade-stats\"><h2>Trade statistics</h2>")
        sb.append(tradeStatsTable(result.global))
        sb.append("</section>")

        sb.append("<section class=\"trades\"><h2>Trades</h2>")
        sb.append(tradesTable(result.trades))
        sb.append("</section>")

        sb.append("<section class=\"monte-carlo\"><h2>Monte Carlo</h2>")
        sb.append(monteCarloSection(result.global))
        sb.append("</section>")

        sb.append("<section class=\"rejections\"><h2>Rejections</h2>")
        sb.append("<p>${result.rejections.size} rejections (see rejections.csv).</p>")
        sb.append("</section>")

        sb.append("<footer><p>Generated by qkt</p></footer>")
        sb.append("</body></html>")
        return sb.toString()
    }

    private fun css(): String =
        """
        body { font-family: system-ui, sans-serif; margin: 24px; color: #222; }
        h1 { margin: 0 0 8px 0; }
        section { margin: 24px 0; }
        .headline { display: flex; gap: 12px; flex-wrap: wrap; }
        .card { padding: 12px 16px; border: 1px solid #ddd; border-radius: 6px; min-width: 140px; }
        .card .label { font-size: 12px; color: #666; }
        .card .value { font-size: 22px; font-weight: 600; }
        .pos { color: #2a7d2a; } .neg { color: #b22; }
        table { border-collapse: collapse; width: 100%; font-size: 13px; }
        th, td { border-bottom: 1px solid #eee; padding: 6px 8px; text-align: right; }
        th:first-child, td:first-child { text-align: left; }
        @media print { .rejections { display: none; } section { page-break-inside: avoid; } }
        """.trimIndent()

    private fun headlineCards(r: PerformanceReport): String {
        fun card(
            label: String,
            value: String,
            classes: String = "",
        ) = "<div class=\"card $classes\"><div class=\"label\">$label</div>" +
            "<div class=\"value\">$value</div></div>"
        return buildString {
            append(
                card(
                    "Total PnL",
                    r.totalPnL.toPlainString(),
                    if (r.totalPnL.signum() >= 0) "pos" else "neg",
                ),
            )
            append(card("Trades", r.tradeCount.toString()))
            append(card("Win rate", r.winRate.toPlainString()))
            append(card("Sharpe", r.sharpeRatio?.toPlainString() ?: "n/a"))
            append(card("Calmar", r.calmarRatio?.toPlainString() ?: "n/a"))
            append(card("Max DD", r.maxDrawdown.toPlainString(), "neg"))
            append(card("Profit factor", r.profitFactor?.toPlainString() ?: "n/a"))
        }
    }

    private fun evidenceSection(e: com.qkt.evidence.EvidenceEnvelope): String =
        buildString {
            append("<table><tbody>")
            append("<tr><td>qkt version</td><td>${html(e.qktVersion)}</td></tr>")
            append("<tr><td>git SHA</td><td>${html(e.gitSha)}</td></tr>")
            append("<tr><td>strategy hash</td><td>${html(e.strategyHash)}</td></tr>")
            e.configHash?.let { append("<tr><td>config hash</td><td>${html(it)}</td></tr>") }
            e.dataset?.let {
                val label =
                    if (it.id != null) {
                        it.id
                    } else if (it.mutableStore) {
                        "mutable local store"
                    } else {
                        "not specified"
                    }
                append("<tr><td>dataset</td><td>${html(label)}</td></tr>")
                it.warning?.let { warning -> append("<tr><td>dataset warning</td><td>${html(warning)}</td></tr>") }
            }
            e.execution?.let {
                append("<tr><td>execution</td><td>${html(it.preset)} (${html(it.broker)})</td></tr>")
                it.fillPriceSource?.let { v -> append("<tr><td>fill price source</td><td>${html(v)}</td></tr>") }
                it.latencyModel?.let { v -> append("<tr><td>latency model</td><td>${html(v)}</td></tr>") }
                it.slippageModel?.let { v -> append("<tr><td>slippage model</td><td>${html(v)}</td></tr>") }
                it.rejectionModel?.let { v -> append("<tr><td>rejection model</td><td>${html(v)}</td></tr>") }
                it.partialFillModel?.let { v -> append("<tr><td>partial-fill model</td><td>${html(v)}</td></tr>") }
                it.venueRules?.let { v -> append("<tr><td>venue rules</td><td>${html(v)}</td></tr>") }
                it.commissionModel?.let { v -> append("<tr><td>cost model</td><td>${html(v)}</td></tr>") }
                it.ocoMode?.let { v -> append("<tr><td>OCO mode</td><td>${html(v)}</td></tr>") }
                it.warning?.let { warning -> append("<tr><td>execution warning</td><td>${html(warning)}</td></tr>") }
            }
            e.accounting?.let {
                it.accountCurrency?.let { ccy -> append("<tr><td>account currency</td><td>${html(ccy)}</td></tr>") }
                it.missingPolicy?.let { policy ->
                    append("<tr><td>FX missing policy</td><td>${html(policy)}</td></tr>")
                }
                it.source?.let { source -> append("<tr><td>FX source</td><td>${html(source)}</td></tr>") }
                if (it.configuredFxSymbols.isNotEmpty()) {
                    append("<tr><td>FX symbols</td><td>${html(it.configuredFxSymbols.toString())}</td></tr>")
                }
                if (it.conversions.isNotEmpty()) {
                    append("<tr><td>FX conversions</td><td>${html(it.conversions.toString())}</td></tr>")
                }
                if (it.warnings.isNotEmpty()) {
                    append("<tr><td>accounting warnings</td><td>${html(it.warnings.joinToString("; "))}</td></tr>")
                }
                it.warning?.let { warning -> append("<tr><td>accounting warning</td><td>${html(warning)}</td></tr>") }
            }
            e.experiment?.let {
                append("<tr><td>experiment</td><td>${html(it.id ?: "unspecified")}</td></tr>")
                it.trialCount?.let { n -> append("<tr><td>trial count</td><td>$n</td></tr>") }
                it.primaryMetric?.let { metric -> append("<tr><td>primary metric</td><td>${html(metric)}</td></tr>") }
                for ((name, window) in it.splits.entries) {
                    append("<tr><td>split.${html(name)}</td><td>${html(window)}</td></tr>")
                }
                it.selectedLabel?.let { label ->
                    append("<tr><td>selected candidate</td><td>")
                    append(html(label))
                    append(" ")
                    append(html(it.selectedParams.toString()))
                    append("</td></tr>")
                }
                if (it.warnings.isNotEmpty()) {
                    append("<tr><td>experiment warnings</td><td>${html(it.warnings.joinToString("; "))}</td></tr>")
                }
                it.warning?.let { warning -> append("<tr><td>experiment warning</td><td>${html(warning)}</td></tr>") }
            }
            e.promotion?.let {
                it.state?.let { state -> append("<tr><td>promotion state</td><td>${html(state)}</td></tr>") }
                it.rationale?.let { rationale ->
                    append("<tr><td>promotion rationale</td><td>${html(rationale)}</td></tr>")
                }
                it.warning?.let { warning -> append("<tr><td>promotion warning</td><td>${html(warning)}</td></tr>") }
            }
            if (e.warnings.isNotEmpty()) {
                append("<tr><td>warnings</td><td>${html(e.warnings.joinToString("; "))}</td></tr>")
            }
            append("</tbody></table>")
        }

    private fun accountingSection(snapshot: com.qkt.accounting.AccountingSnapshot): String =
        buildString {
            append("<table><tbody>")
            append("<tr><td>account currency</td><td>${html(snapshot.accountCurrency)}</td></tr>")
            append("<tr><td>FX missing policy</td><td>${html(snapshot.missingPolicy)}</td></tr>")
            append("<tr><td>FX source</td><td>${html(snapshot.source)}</td></tr>")
            if (snapshot.configuredSymbols.isNotEmpty()) {
                append("<tr><td>configured FX symbols</td><td>${html(snapshot.configuredSymbols.toString())}</td></tr>")
            }
            if (snapshot.conversions.isNotEmpty()) {
                append("<tr><td>observed conversions</td><td>")
                append(
                    html(
                        snapshot.conversions.joinToString("; ") {
                            "${it.from}->${it.to} rate=${it.rate.toPlainString()} timestamp=${it.timestamp} source=${it.source}"
                        },
                    ),
                )
                append("</td></tr>")
            }
            if (snapshot.warnings.isNotEmpty()) {
                append("<tr><td>warnings</td><td>${html(snapshot.warnings.joinToString("; "))}</td></tr>")
            }
            append("<tr><td>cost kinds</td><td>${html(snapshot.supportedCostKinds.joinToString(", "))}</td></tr>")
            append("</tbody></table>")
        }

    private fun html(s: String): String =
        s
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")

    private fun drawdownTable(periods: List<DrawdownPeriod>): String {
        if (periods.isEmpty()) return "<p>No drawdowns above threshold.</p>"
        return buildString {
            append("<table><thead><tr>")
            append("<th>Peak</th><th>Trough</th><th>Recovery</th><th>Depth</th>")
            append("<th>Duration ms</th><th>Status</th></tr></thead><tbody>")
            for (p in periods) {
                append("<tr><td>${p.peakTimestamp}</td><td>${p.troughTimestamp}</td>")
                append("<td>${p.recoveryTimestamp ?: "ongoing"}</td>")
                append("<td>${p.depthPct.toPlainString()}</td>")
                append("<td>${p.durationMs}</td>")
                append("<td>${if (p.ongoing) "ongoing" else "recovered"}</td></tr>")
            }
            append("</tbody></table>")
        }
    }

    private fun tradeStatsTable(r: PerformanceReport): String =
        buildString {
            append("<table><tbody>")
            append("<tr><td>Average win</td><td>${r.avgWin.toPlainString()}</td></tr>")
            append("<tr><td>Average loss</td><td>${r.avgLoss.toPlainString()}</td></tr>")
            append("<tr><td>Largest win</td><td>${r.largestWin.toPlainString()}</td></tr>")
            append("<tr><td>Largest loss</td><td>${r.largestLoss.toPlainString()}</td></tr>")
            append("<tr><td>Max consecutive losses</td><td>${r.maxConsecutiveLosses}</td></tr>")
            append("</tbody></table>")
        }

    private fun tradesTable(trades: List<TradeRecord>): String {
        val sample =
            if (trades.size <= config.tradeTableHead + config.tradeTableTail) {
                trades
            } else {
                trades.take(config.tradeTableHead) + trades.takeLast(config.tradeTableTail)
            }
        return buildString {
            append("<table><thead><tr>")
            append("<th>Timestamp</th><th>Strategy</th><th>Symbol</th><th>Side</th>")
            append("<th>Qty</th><th>Price</th><th>riskUsd</th><th>Realized</th>")
            append("<th>Native</th><th>Account</th><th>FX</th><th>Pos Before</th><th>Pos After</th>")
            append("<th>Strat Before</th><th>Strat After</th><th>Contract</th><th>Notional</th>")
            append("</tr></thead><tbody>")
            for (r in sample) {
                val contractSize = r.contractSize ?: java.math.BigDecimal.ONE
                val fillNotional =
                    r.trade.price
                        .multiply(r.trade.quantity.abs())
                        .multiply(contractSize)
                append("<tr>")
                append("<td>${r.trade.timestamp}</td>")
                append("<td>${r.strategyId}</td>")
                append("<td>${r.trade.symbol}</td>")
                append("<td>${r.trade.side}</td>")
                append("<td>${r.trade.quantity.toPlainString()}</td>")
                append("<td>${r.trade.price.toPlainString()}</td>")
                append("<td>${r.riskUsd?.toPlainString() ?: "n/a"}</td>")
                append("<td>${r.realized.toPlainString()}</td>")
                append(
                    "<td>${r.nativeRealized?.toPlainString() ?: "n/a"}" +
                        "${r.nativeCurrency?.let { " $it" } ?: ""}</td>",
                )
                append(
                    "<td>${r.accountRealized?.toPlainString() ?: "n/a"}" +
                        "${r.accountCurrency?.let { " $it" } ?: ""}</td>",
                )
                append("<td>${r.fxRate?.toPlainString() ?: "identity"}</td>")
                append(
                    "<td>${r.accountPositionBefore?.quantity?.toPlainString() ?: "n/a"} " +
                        "@${r.accountPositionBefore?.avgEntryPrice?.toPlainString() ?: "n/a"}</td>",
                )
                append(
                    "<td>${r.accountPositionAfter?.quantity?.toPlainString() ?: "n/a"} " +
                        "@${r.accountPositionAfter?.avgEntryPrice?.toPlainString() ?: "n/a"}</td>",
                )
                append(
                    "<td>${r.strategyPositionBefore?.quantity?.toPlainString() ?: "n/a"} " +
                        "@${r.strategyPositionBefore?.avgEntryPrice?.toPlainString() ?: "n/a"}</td>",
                )
                append(
                    "<td>${r.strategyPositionAfter?.quantity?.toPlainString() ?: "n/a"} " +
                        "@${r.strategyPositionAfter?.avgEntryPrice?.toPlainString() ?: "n/a"}</td>",
                )
                append("<td>${r.contractSize?.toPlainString() ?: "1"}</td>")
                append("<td>${fillNotional.toPlainString()}</td>")
                append("</tr>")
            }
            append("</tbody></table>")
            if (sample.size < trades.size) {
                append("<p>Showing first ${config.tradeTableHead} and last ${config.tradeTableTail} ")
                append("of ${trades.size} trades. Full list in trades.csv.</p>")
            }
        }
    }

    private fun monteCarloSection(r: PerformanceReport): String {
        val mc =
            r.monteCarlo ?: return "<p>Insufficient trades for Monte Carlo " +
                "(need ${config.minTradesForMonteCarlo}+).</p>"
        return buildString {
            append("<table><tbody>")
            append("<tr><td>Simulations</td><td>${mc.simulations}</td></tr>")
            append("<tr><td>P5 final equity</td><td>${mc.finalEquityP5.toPlainString()}</td></tr>")
            append("<tr><td>P50 final equity</td><td>${mc.finalEquityP50.toPlainString()}</td></tr>")
            append("<tr><td>P95 final equity</td><td>${mc.finalEquityP95.toPlainString()}</td></tr>")
            append("<tr><td>P5 max DD</td><td>${mc.maxDrawdownP5.toPlainString()}</td></tr>")
            append("<tr><td>P95 max DD</td><td>${mc.maxDrawdownP95.toPlainString()}</td></tr>")
            append("<tr><td>P(final &lt; 0)</td><td>${mc.probabilityNegativeFinal.toPlainString()}</td></tr>")
            append("</tbody></table>")
            append(SvgChart.fanChart(mc.equityFanByTradeIndex, width = 1000, height = 360))
        }
    }
}
