package com.qkt.backtest.report

import com.qkt.backtest.BacktestResult
import java.nio.file.Files
import java.nio.file.Path

/**
 * Renders a [com.qkt.backtest.BacktestResult] as a self-contained HTML report —
 * headline cards, equity / drawdown / Monte-Carlo charts, per-strategy breakdowns,
 * and head / tail tables of individual trades.
 *
 * No external assets: all CSS, SVG, and data are inlined in the produced string,
 * so the report renders identically when opened offline or attached to an email.
 * Visual + statistical knobs live on [HtmlReportConfig].
 */
class HtmlReportWriter(
    private val config: HtmlReportConfig = HtmlReportConfig(),
) {
    /** Render the report and write it to [path]. Overwrites any existing file. */
    fun write(
        result: BacktestResult,
        path: Path,
    ) {
        Files.writeString(path, render(result))
    }

    /** Build the full HTML report as a single string. */
    fun render(result: BacktestResult): String {
        val sb = StringBuilder()
        sb.append("<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">")
        sb.append("<title>qkt backtest report</title>")
        sb.append("<style>${css()}</style></head><body>")

        sb.append("<header><h1>qkt backtest report</h1></header>")
        sb.append("<section class=\"headline\">")
        sb.append(HtmlPerformanceTables.headlineCards(result.global))
        sb.append("</section>")

        result.evidence?.let {
            sb.append("<section class=\"evidence\"><h2>Run evidence</h2>")
            sb.append(HtmlEvidenceTable.render(it))
            sb.append("</section>")
        }
        result.accounting?.let {
            sb.append("<section class=\"accounting\"><h2>Accounting</h2>")
            sb.append(HtmlAccountingTable.render(it))
            sb.append("</section>")
        }
        result.runawayBreaker?.let {
            sb.append("<section class=\"runaway-breaker\"><h2>Runaway breaker</h2>")
            sb.append(HtmlRunawayBreakerTable.render(it))
            sb.append("</section>")
        }

        sb.append("<section class=\"equity\"><h2>Equity</h2>")
        sb.append(
            SvgChart.lineChartWithUnderwater(
                curve = result.global.equityCurve,
                drawdowns = result.global.drawdownPeriods,
                width = 1000,
                height = 360,
            ),
        )
        sb.append("</section>")

        sb.append("<section class=\"drawdowns\"><h2>Drawdown periods</h2>")
        sb.append(HtmlPerformanceTables.drawdownTable(result.global.drawdownPeriods))
        sb.append("</section>")

        sb.append("<section class=\"trade-stats\"><h2>Trade statistics</h2>")
        sb.append(HtmlPerformanceTables.tradeStatsTable(result.global))
        sb.append("</section>")

        sb.append("<section class=\"trade-audit\"><h2>Trade audit</h2>")
        sb.append(HtmlTradeAuditTable.render(TradeAuditSummaries.from(result)))
        sb.append("</section>")

        sb.append("<section class=\"trades\"><h2>Trades</h2>")
        sb.append(HtmlTradesTable.render(result.trades, config))
        sb.append("</section>")

        sb.append("<section class=\"monte-carlo\"><h2>Monte Carlo</h2>")
        sb.append(HtmlPerformanceTables.monteCarloSection(result.global, config))
        sb.append("</section>")

        sb.append("<section class=\"rejections\"><h2>Rejections</h2>")
        sb.append("<p>${result.rejections.size} rejections (see rejections.csv).</p>")
        sb.append("</section>")

        sb.append("<footer><p>Generated by qkt</p></footer>")
        sb.append("</body></html>")
        return sb.toString()
    }

    private fun css(): String =
        """
        body { font-family: system-ui, sans-serif; margin: 24px; color: #222; }
        h1 { margin: 0 0 8px 0; }
        section { margin: 24px 0; }
        .headline { display: flex; gap: 12px; flex-wrap: wrap; }
        .card { padding: 12px 16px; border: 1px solid #ddd; border-radius: 6px; min-width: 140px; }
        .card .label { font-size: 12px; color: #666; }
        .card .value { font-size: 22px; font-weight: 600; }
        .pos { color: #2a7d2a; } .neg { color: #b22; }
        table { border-collapse: collapse; width: 100%; font-size: 13px; }
        th, td { border-bottom: 1px solid #eee; padding: 6px 8px; text-align: right; }
        th:first-child, td:first-child { text-align: left; }
        @media print { .rejections { display: none; } section { page-break-inside: avoid; } }
        """.trimIndent()
}
